### ISSUE TITLE
TRADER

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#100]
https://github.com/researchart/rose6icse/tree/master/submissions/available/TRADER

| Corresponding | Name          | ID        | Email                  |
| ------------- | ------------- | --------- | ---------------------- |
| Yes           | Guanhong Tao  | Gwinhen   | taog@purdue.edu        |
|               | Shiqing Ma    |           | shiqing.ma@rutgers.edu |
|               | Yingqi Liu    |           | liu1751@purdue.edu     |
|               | Qiuling Xu    |           | xu1230@purdue.edu      |
|               | Xiangyu Zhang |           | xyzhang@cs.purdue.edu  |

# applying for Available   and Reusable

**Comment by artifact-review** [comment]
The authors apply for "Available" badge

- Provided docker image eases the installation process.
- Straightforward running instructions

Comments:
- The authors should add `--dataset` option to the script reproducing Table 3, 4, and 5
- The data obtained was slightly different from data in the paper but that might be due to hardware configurations, so it's fine.

**Decision:** Accepted

**Comment by timm** [comment]
Dear @artifact-review : what about "reusable":Functional + very carefully documented and well-structured to the extent that reuse and repurposing is facilitated. In particular, norms and standards of the research community for artifacts of this type are strictly adhered to.

@grumpyreviewer : I look forward to your review

**Comment by artifact-review** [comment]
About "Reusable" badge:
The `README.md" file provides detailed instructions on how to run the python program with different options to reproduce the results in the paper. I have no problem running the program therefore my call is: **Accept** the badge. 

My only concern is that, even though the authors applied for both "Available" and "Reusable" badges, the submission is made only under "Available" category. I could not find their submission under "Reusable" (https://github.com/researchart/rose6icse/tree/master/submissions/reusable). Therefore, @timm it's your call to make the final decision on whether to give the authors "reusable" badge or not.

**Comment by timm** [comment]
@artifact-review : thank you for the care for your review. see https://github.com/researchart/rose6icse/blob/master/submissions/available/TRADER/STATUS.md (where they apply for both badges)

current status: reusable=available=yes (unless @grumpyreviewer objects)

**Comment by grumpyreviewer** [comment]
I can run the artifact and the instructions are clear. So _reusable_ looks fine to me.

Concerning _available_ though, I could not find any doi. Did I miss it somehow?

**Comment by Gwinhen** [comment]
Sorry for the missing DOI. The artifact was published on Zenodo. [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3677026.svg)](https://doi.org/10.5281/zenodo.3677026)

I have also made the PR. Thank you!
