### ISSUE TITLE
code-level-modelchecking

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#102]
https://github.com/researchart/rose6icse/tree/master/submissions/available/code-level-modelchecking
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/code-level-modelchecking

- Schwartz-Narbonne, Daniel (Corresponding author)
  - email: dsn@amazon.com
  - github id: danielsn

- Nathan Chong
  - email: ncchong@amazon.com
  - github id: nchong-at-aws

- Felipe R. Monteiro
  - email: rms.felipe@gmail.com
  - github id: feliperodri
  
- Konstantinos Kallas
  - email: kallas@seas.upenn.edu
  - github id: angelhof

- Michael Tautschnig
  - email: tautschn@amazon.co.uk
  - github id: tautschnig

- Mark Tuttle
  - email: mrtuttle@amazon.com
  - github id: markrtuttle

- Byron Cook
  - email: byron@amazon.com
  - github id: johnbyroncook
  
- Serdar Tasiran
  - email: tasirans@amazon.com
  - github id: stasiran

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by artifact-review** [comment]
@danielsn: The `make` command yielded errors due to missing "goto-analyzer" executable file. Shouldn't we need `goto-analyzer` in the prebuilt binaries in order to execute?

**Comment by dmz-peerreview** [comment]
Dear authors, 

Thanks for your submission. Overall, I was surprised how long the compilation took. I would have been helpful to mention the compilation time (about n minutes on system x, up to half an hour, ...).

Other than that:
* the package provides pre-compiled binaries for all major platforms,
* the source code is publicly avialable under a proper license,
* the source code compiled under Ubuntu 18.04 following the instructions,
* it has unique identifier (i.e. commit hash, version tag),
* it offers a comprehensive documentation, and 
* it provides an example

From my point of view, the software tool should be functional/avialable and reusable.

**Comment by karkhaz** [comment]
@artifact-review thank you for your comment. `goto-analyzer` isn't needed to reproduce the artifact; we use it to build a final HTML report, but it's not needed for the data presented in the paper. However, we're happy to open a pull request to add this binary to the artifact anyway (if you prefer---please let us know how to proceed).

**Comment by artifact-review** [comment]
@karkhaz Thanks for your response. In that case, there is no need for a new pull request.

**Comment by artifact-review** [comment]
The authors apply for **Available** and **Reusable** badges.  
The tool is publicly available and GitHub along with detailed instructions and helpful prebuilt binaries for several major platforms.

Decision: **Accepted**
