### ISSUE TITLE
deepimportance

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#103]
https://github.com/researchart/rose6icse/tree/master/submissions/available/deepimportance
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/deepimportance

**Name:** Hasan Ferit Eniser (**Corresponding author**)  
**email:** hfeniser@mpi-sws.org  
**GitHub ID:** [hasanferit](https://github.com/hasanferit)  

**Name:** Simos Gerasimou  
**email:** simos.gerasimou@york.ac.uk  
**GitHub ID:** [gerasimou](https://github.com/gerasimou)  

**Name:** Alper Sen  
**email:** alper.sen@boun.edu.tr  
**GitHub ID:** [dependable-systems](https://github.com/dependable-systems)   

**Name:** Alper Cakan  
**email:** alper.cakan@boun.edu.tr  
**GitHub ID:** [alpercakan](https://github.com/alpercakan)  

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by ai-sta-website** [comment]
@DeepImportance 

During the evaluation, we were encountering a bunch of import errors. Even if we tried to solve import errors of example scripts, the script throws exception. It seems to us that you were using some IDE for the development, and the IDE makes complex settings for their project. We couldn't find further instructions to solve this problem. See the following message:

````
XXX@XXX:~/review/deepimportance_code_release/reproduce$ source ../../env-deepimportance/bin/activate
(env-deepimportance) XXX@XXX:~/review/deepimportance_code_release/reproduce$ pip list
[33mDEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support[0m
Package                       Version  
----------------------------- ---------
absl-py                       0.9.0    
astor                         0.8.1    
backports.functools-lru-cache 1.6.1    
backports.weakref             1.0.post1
cleverhans                    3.0.1    
cloudpickle                   1.2.2    
cycler                        0.10.0   
decorator                     4.4.1    
enum34                        1.1.6    
funcsigs                      1.0.2    
futures                       3.3.0    
gast                          0.3.3    
grpcio                        1.26.0   
h5py                          2.10.0   
Keras                         2.2.2    
Keras-Applications            1.0.4    
Keras-Preprocessing           1.0.2    
kiwisolver                    1.1.0    
Markdown                      3.1.1    
matplotlib                    2.2.5    
mnist                         0.2.2    
mock                          3.0.5    
networkx                      2.2      
nose                          1.3.7    
numpy                         1.14.5   
Pillow                        6.2.2    
pip                           20.0.2   
protobuf                      3.11.3   
pycodestyle                   2.5.0    
pyparsing                     2.4.6    
python-dateutil               2.8.1    
pytz                          2019.3   
PyWavelets                    1.0.3    
PyYAML                        5.3      
scikit-image                  0.14.5   
scikit-learn                  0.20.4   
scipy                         1.2.3    
setuptools                    39.1.0   
six                           1.14.0   
subprocess32                  3.5.4    
tensorboard                   1.10.0   
tensorflow                    1.10.0   
tensorflow-probability        0.9.0    
termcolor                     1.1.0    
Werkzeug                      1.0.0    
wheel                         0.34.2   
(env-deepimportance) XXX@XXX:~/review/deepimportance_code_release/reproduce$ python TABLE2_FIGURE4.py
Traceback (most recent call last):
  File "TABLE2_FIGURE4.py", line 1, in <module>
    from utils import get_layer_outs_new, preprocess_image, get_trainable_layers
ImportError: No module named utils
(env-deepimportance) XXX@XXX:~/review/deepimportance_code_release/reproduce$ cp *.py ../
(env-deepimportance) XXX@XXX:~/review/deepimportance_code_release/reproduce$ cd ..
(env-deepimportance) XXX@XXX:~/review/deepimportance_code_release$ python TABLE2_FIGURE4.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "TABLE2_FIGURE4.py", line 34, in <module>
    X_paths, Ys = load_driving_data()
  File "/home/XXX/review/deepimportance_code_release/utils.py", line 73, in load_driving_data
    with open(path + 'final_example.csv', 'r') as f:
IOError: [Errno 2] No such file or directory: 'driving_data/final_example.csv'
(env-deepimportance) XXX@XXX:~/review/deepimportance_code_release$ python TABLE3_MNIST.py --approach idc --rel_neurons 6
Traceback (most recent call last):
  File "TABLE3_MNIST.py", line 1, in <module>
    from reproduce.manipulate import add_wn_frame, add_white_noise, add_wn_random
ImportError: No module named reproduce.manipulate
````


Could you provide a step-by-step setup, to launch your experiments via command line?

**Comment by gorocketsgo** [comment]
This artifact includes the source code of DeepImportance and the scripts to reproduce the results in their paper. The authors apply for the REUSABLE and AVAILABLE badges. 

First, the GitHub repository does not have a DOI. Please either upload your source code to Zenodo or following instructions in https://guides.github.com/activities/citable-code/ to generate a DOI. 

When I set up the environment following INSTALL.md, I run into the issue below after running `pip install Tensorflow==1.10.0`.

> File "/ICSE-2020-Artifact-Evaluation/DeepImportance/env/bin/pip", line 5, in <module>
>     from pip._internal.cli.main import main
> ImportError: No module named _internal.cli.main

I installed Python 2.7.17 and created a virtual environment using virtualenv. The solution for this issue is to run `python -m pip install --upgrade pip`. After resolving this issue, I successfully installed the required libraries. Yet overall it is cumbersome to manually set up the environment. I suggest the authors provide a Docker image so that users can simply run your tool in Docker.

I got two errors when running the scripts to reproduce the results.

> Traceback (most recent call last):
>   File "TABLE2_FIGURE4.py", line 1, in <module>
>     from utils import get_layer_outs_new, preprocess_image, get_trainable_layers
> ImportError: No module named util

> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "TABLE4.py", line 2, in <module>
>     from reproduce.manipulate import add_wn_all, add_wn_frame, add_white_noise, add_wn_random
> ImportError: No module named reproduce.manipulate

This artifact only provides several scripts to reproduce the results in the paper. There is no documentation of the tool. For example, it is unclear which script I should run to generate the importance-driven coverage of a neural network given its test set and what arguments to pass into that script. Such documentation is critical to make your tool reusable by others. 

My initial decision is REJECT for both badges. But I am willing to change my decision to ACCEPT, if the authors can provide 1) a DOI to make the repo permanently available and citable, 2) a solution to those two errors above, and 3) clear documentation about how to run your tool.

**Comment by minkull** [comment]
@hasanferit over to you

**Comment by timm** [comment]
@hasanferit
dear authors, 5 days ago a request was made for new materials. was that done as a pull request?

 if not, we might have to pass on this one

@gorocketsgo @random-friendly-dude 
dear reviewers-
have u checked for updates?

**Comment by gorocketsgo** [comment]
@timm I just checked the repository. Nothing has been updated yet. I also haven't received any clarification from the authors. As a result, I will keep my initial REJECT decision for both badges.

**Comment by timm** [comment]
@gorocketsgo : thanks for your efforts. much appreciated.

**Comment by minkull** [comment]
No badge awarded.
