### ISSUE TITLE
heapster

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#104]
https://github.com/researchart/rose6icse/tree/master/submissions/available/heapster
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/heapster

- Manuel Benz
	- email: manuel.benz@upb.de
	- github id: mbenz89

## Author
```tex
\author{Manuel Benz}
\affiliation{
    \department{Department of Computer Science}
    \institution{Paderborn University}
    \country{Germany}
}
\email{manuel.benz@upb.de}

\author{Erik Krogh Kristensen}
\affiliation{
  \department{Department of Computer Science}
  \institution{Aarhus University}
  \country{Denmark}
}
\email{erik@cs.au.dk}

\author{Linghui Luo}
\affiliation{
    \department{Department of Computer Science}
    \institution{Paderborn University}
    \country{Germany}
}
\email{linghui.luo@upb.de}

\author{Nataniel P. Borges Jr. }
\affiliation{
    %\department{Department of Computer Science}
    \institution{CISPA Helmholtz Center for Information Security}
    \country{Germany}
}
\email{nataniel.borges@cispa.saarland}

\author{Eric Bodden}
\affiliation{
    %\department{Department of Computer Science}
    \institution{Paderborn University \& Fraunhofer IEM}
    \country{Germany}
}
\email{eric.bodden@upb.de}

\author{Andreas Zeller}
\affiliation{
    %\department{Department of Computer Science}
    \institution{CISPA Helmholtz Center for Information Security}
    \country{Germany}
}
\email{zeller@cispa.saarland}
```

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by icse2020review** [comment]
The authors clearly explain the steps required to install Heapster and re-conduct the experiments. While Heapster source code is not provided as a GitHub repository, the Heapster tool can be downloaded from a zenodo repository. They also provided Dockerfile to create a docker image with a ready-to-use setup. All in all, the artifacts provided satisfy the the reusable and available badges requirements.

**Comment by gh-artifact-1763** [comment]
I did not have time to download the 10 Gb Docker image ... nor the bandwidth. This seems like a serious constraint. Is it not possible to host on DockerHub, so that e.g. your Linux OS can be shared (this is after all the value of Docker)

It also strikes me as odd that the benchmarks could not be separated into another file. Right now the entire 10 gigs has to be downloaded even if all we want is a benchmark.

I think the artifact would be more reusable if the authors separated the files into tool, benchmarks, and results. Is this possible?

**Comment by timm** [comment]
@icse2020review is quite definite: this artifact is reusable and available. But before I declare it so, please comment on   @gh-artifact-1763 's question about  simplifying the downloads

**Comment by timm** [comment]
Anything further?
