### ISSUE TITLE
junwenyang

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#116]
https://github.com/researchart/rose6icse/tree/master/submissions/available/junwenyang
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/junwenyang

name github_id

junwen yang: manageconstraints

utsav: whoisutsav

Authors: Junwen Yang , Utsav Sethi , Cong Yan , Alvin Cheung , Shan Lu

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by github-anonymous** [comment]
### General remarks:

* The STATUS.md file does not contain information about the applied badges and why the authors think they deserve them
* The original paper is not part of the repo or linked, so it is hard to compare the results with the paper.

### Basic Requirement: Functional (reject):

* Please change the command for pulling the Docker image to "docker pull managedataconstraints/data-constraints-analyzer:first". The default tag is "latest", which is not available for the image.
* Reproduced experiments:
  * Figure 2: OK
  * Table 4, 5, 6, 10: Throws an error when processing app gitlabhq (see screenshot below)
  * Table 7: Throws an error when processing app gitlabhq; Following call "ruby api_breakdown_spread_sheets.rb" throws error "api_breakdown_spread_sheets.rb:59:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)"
  * Table 8: OK
  * Table 9: Command "python extract_breakdown.py" exits with "File "extract_breakdown.py", line 1, in <module> import xlrd ImportError: No module named xlrd"
  * User Study: OK (the second link to the raw results is dead)
  * Did not try to run on other application

![Table 4](https://user-images.githubusercontent.com/57346494/74519460-06317200-4f16-11ea-878d-e1541b66007d.PNG)


### Reusable Badge (reject)
* The INSTALL.md description points to Excel files on GDrive for the results. However, it is not clear to me whether these results are produced by the scripts I am running (I assume not) or if they have been statically prepared by the authors. It is not clear where the scripts actually store their outputs to.
* For compatibility, readability, and reusability reasons, it would be better to write to the results to a .csv file and not to .xlxs



### Available Badge (reject):
* The artifact is spread across several repositories (mostly DockerHub and GoogelDrive). Both do not qualify as "publicly accessible archival repository". There is no DOI provided for the artifact.

**Comment by timm** [comment]
@data-track-reviewer : I look forward to your review.

**Comment by manageconstraints** [comment]
Sorry for the late reply. The public doi has been put into the abstract file: https://osf.io/yaefh/ together with the source code and the original paper.

**Comment by manageconstraints** [comment]
Also, the failure of Table 4, 5, 6, 7, 10 happens since one dependent tool has shut down, we are revising it asap and will update the docker.

**Comment by ghost** [comment]
Not much to add at the moment. @github-anonymous comments are still relevant and I agree that at the moment no badge can be awarded.

With respect to available, the osf.io project appears to fix this issue only partially. The readme.md is now inconsistent with what the artifact really is. In particular, it only refers to a docker image. But in fact, it is both: the open science framework project that ensures availability and the docker image that ensures facilitation of reusing and re-purposing. 

This artifact requires better structuring and organization. Should there not be one landing page (e.g. on OSF) referring to each part of this artifact (including the docker image and the installation guide)? I suggest to also update the files submitted to this github.

**Comment by manageconstraints** [comment]
Thanks for your comments, we are fixing the problems of Table 4, 5, 6, 7, 10 which are caused by the outside website by removing the outside dependency. We will upload the docker image together to the osf.io once we are done.

**Comment by manageconstraints** [comment]
We have incorporated your feedback into the pull request here:
https://github.com/researchart/rose6icse/pull/184

We hope this addresses the reviewers' concerns.

**Comment by timm** [comment]
@github-anonymous 
@data-track-reviewer
the authors update their work 3 days ago. can u look again and say clearly If u recommend any badgers?

thank!

**Comment by ghost** [comment]
Great job with improving the documentation. I would now recommend **accept with respect to the *availability* badge**.

A minor issue: there is a link in readme.md that should point to install.md but does point to readme.md.

Since completeness and excercisability was not in question beyond the xls, I did recheck those aspects in particular. It seems that now there is much more use of csv as well as a very clear description on how the output of the tools relates to the paper results that are shared as well (in form of xlsx). I therefor also do recommend **accept with respect to the *reusable* badge**.

**Comment by github-anonymous** [comment]
I agree with the recommendation of @data-track-reviewer
