### ISSUE TITLE
rigby_mirsaeedi_turnover

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#120]
https://github.com/researchart/rose6icse/tree/master/submissions/available/rigby_mirsaeedi_turnover
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/rigby_mirsaeedi_turnover

- Ehsan Mirsaeedi (Corresponding Author)
  - Email: mirsaeedi@outlook.com
  - Github: [mirsaeedi](https://github.com/mirsaeedi)

- Peter C. Rigby 
  - Email: rigbypc@gmail.com
  - Github: [rigbypc](https://github.com/rigbypc)

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by timm** [comment]
@AnAnonymousReviewer and @data-track-reviewer : I look forward to your reviews

**Comment by ghost** [comment]
This artifact consists of a tool and a replication package. Both are documented, although rather briefly. They are made available through github and no DOI is provided. One can consider github to provide a _"a unique identifier for the object"_

## Reusable: Leaning towards reject
It feels like the brevity of documentation cannot really be seen as supporting reusing and re-purposing. While I agree that the packaging is a good step into this direction, especially the role of the tool as part of this artifact remains a bit unclear. It seems to be based on the 2016 paper? Standalone, it appears to be reusable. Together with this replication package, more guidance could be wished for to fulfill the _"very carefully documented and well-structured to the extent that reuse and repurposing is facilitated"_ criteria.

## Available: Leaning towards reject
Replication appears to include a step where a database backup must be obtained from google drive. This appears to violate the available badge criteria. Yet, managing large data is of course an issue. Has any platform for scientific data sharing be considered?

**Comment by AnAnonymousReviewer** [comment]
The authors ask for the badges "reusable" and "available". Both have the criteria of the level "functional" as preconditions. I am using the criteria from [1] and [2]. 

I am assuming that the artifact under review is the tool "RelationalGit". 

In the following, I will discuss the criteria for these badges. 


# Functional

## Documented
Requirement: "At minimum, an inventory of artifacts is included, and sufficient description provided to enable the artifacts to be exercised."
 
The documentation is quite complete, but difficult to understand. I could run the tool based on the instructions. 

One problem was that the authors asked to install the latest version of .Net Core although it didn't work with .Net Core version 3.1 and I had to install version 2.2.

Overall, installation documentation is complete for .Net users. I am not sure whether it would be appropriate for users with basic knowledge in this field. 

The steps to reproduce the paper results were difficult to understand. For example, it is not clear what <no_reviews_sim_id> means. We figured out that it may mean that one should provide the id of a simulation run that has no reviews. We had to spend several hours to figure out the meaning and reproduce the results. 

## Consistent
Requirement: "The artifacts are relevant to the associated paper, and contribute in some inherent way to the generation of its main results."

I got the results shown in the paper.

## Complete
Requirement: "To the extent possible, all components relevant to the paper in question are included. (Proprietary artifacts need not be included. If they are required to exercise the package then this should be documented, along with instructions on how to obtain them. Proxies for proprietary data should be included so as to demonstrate the analysis.)"

The submission itself does not contain any tool, but refers to RelationalGit using the .NET package manager nuget (https://www.nuget.org/packages/RelationalGit). It additionally describes the needed proprietary artefacts (with the problem with the .Net version mentioned above). 

## Exercisable
Requirement: "Included scripts and/or software used to generate the results in the associated paper can be successfully executed, and included data can be accessed and appropriately manipulated."

The instructions at https://github.com/researchart/rose6icse/blob/master/submissions/available/rigby_mirsaeedi_turnover/README.md were sufficient to generate the results. 

However, there were many exceptions, like "SystemArgumentException: Invalid recommendationStrategy", so it is not clear whether the tool actually does what is expected or whether there are bugs in the tool. 

--> All criteria are met, so the artifact is functional, although the documentation was difficult to understand. 


# Available  

Requirement: "placed on a publicly accessible archival repository. A DOI or link to this repository along with a unique identifier for the object is provided."

The artifact is available at https://www.nuget.org/packages/RelationalGit. However, I am not sure whether nuget can be considered an archival repository, i.e. whether it guarantees that the artifact will remain available (and cannot be removed). Please advise in the rebuttal and either refer to the nuget archival policy or provide an additional archival link, e.g. using Zenodo. 

The data for replicating the result is only available via OneDrive, but I think it is enough if the tool itself was available with some example data. The whole data to reproduce the results in the paper does not have to be available in an archival repository in my interpretation of the badge requirements. 

--> If the authors make the artifact available on an archival repository, I will suggest to award the badge "Available". Please do so in the rebuttal period. 


# Reusable  

Requirement: "The artifacts associated with the paper are of a quality that significantly exceeds minimal functionality. That is, they have all the qualities of the Artifacts Evaluated – Functional level, but, in addition, they are very carefully documented and well-structured to the extent that reuse and repurposing is facilitated. In particular, norms and standards of the research community for artifacts of this type are strictly adhered to."

The artifact's source code is available at https://github.com/CESEL/RelationalGit, thus it is possible for other researchers to reuse and repurpose it. 

The documentation on the starting page is detailed and did help to reproduce the results. At the same time, however, it took us a while to figure out what the instructions mean (see point about no_review_sim_id above, as an example). Thus, although the documentation is detailed, it is not precise enough to qualify as "very carefully documented" in my opinion. 

Additionally, individual classes are not documented. I looked at the following randomly selected classes: 

https://github.com/CESEL/RelationalGit/tree/master/src/RelationalGit.Data/Models
* Commit.cs
* PullRequest.cs

https://github.com/CESEL/RelationalGit/blob/master/src/RelationalGit.Calculation/Program.cs

https://github.com/CESEL/RelationalGit/blob/master/src/RelationalGit.Recommendation/Strategies/Spreading/SpreadingKnowledgeShareStrategyBase.cs

Additionally, I did not see any guidance for developers that described the source code structure, aspects like important interfaces to implement when adding strategies or similar.

--> Thus, I suggest not to award the badge "reusable". 

[1] https://conf.researchr.org/track/icse-2020/icse-2020-Artifact-Evaluation#Call-for-Submissions
[2] https://www.acm.org/publications/policies/artifact-review-badging

**Comment by rigbypc** [comment]
I believe we may have missed the rebuttal period. We would like to state that this paper is in no way based on the code from the 2016 paper by different authors. We completely re-implemented chRev from scratch without contacting those authors as well as creating novel review recommenders. For the available badge, I believe the main concern is a DOI and archive, I believe the corresponding and first author could easily create this (@mirsaeedi). 

I appreciate all your work and now have a better understanding of what you're looking for. 

Thanks, Peter

**Comment by AnAnonymousReviewer** [comment]
Dear Peter,

I am open to reconsider my assessment if a DOI is provided. 

Best regards
AnAnonymousReviewer

**Comment by timm** [comment]
@rigbypc

>  I believe we may have missed the rebuttal period.

no. rebuttal is now.

 but fyi  final decisions are Monday so now is the time to generate that DOI. which is easy to do. just register thes repo at Zenodo and make a release. instant DOI (u even et a pretty badge to add to the GitHub site)

**Comment by timm** [comment]
Currently we are at available, not reusable.

**Comment by rigbypc** [comment]
I have made the GitHub DOI: https://doi.org/10.5281/zenodo.3678570

I have tried for the last couple days to upload the dataset and have a reserved DOI. If it fails again, I will try breaking up the Data DOI: https://doi.org/10.5281/zenodo.3678551

Thanks,
Peter

**Comment by minkull** [comment]
@rigbypc What issue you are facing with the upload of the dataset to Zenodo?

PS: decision will be made by end of 24th Feb AoE.

**Comment by minkull** [comment]
Thank you all for the discussions.

The data are only provided in Google Drive and no DOI. No further updates from @rigbypc on attempts to upload to Zenodo. Unfortunately, we regret that the decision is no badge.

**Comment by rigbypc** [comment]
I realize it's after the deadline. I'm on parental leave and don't get much time for research work. I was able to break the files up and after many attempts Zenodo accepted it:
Data DOI: https://doi.org/10.5281/zenodo.3678551

Also GitHub DOI: https://doi.org/10.5281/zenodo.3678570

Cheers,
Peter

**Comment by minkull** [comment]
We've already sent the decisions to ICSE's proceeding chairs, but I'll update the spreadsheet and send it again with "available" for your paper. Hopefully, there is still enough time for them to include it.

**Comment by rigbypc** [comment]
Where they able to include it? Sorry again for being a day late. I'm on parental leave and my research time is very limited. Thanks. 

Peter

**Comment by minkull** [comment]
I believe so. I've just emailed the proceedings chairs to double check.

**Comment by rigbypc** [comment]
Sorry to bother you again. Ping :-)

**Comment by minkull** [comment]
Hi, sorry, yes, they were able to include it
