### ISSUE TITLE
rvantonderTailoring

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#121]
https://github.com/researchart/rose6icse/tree/master/submissions/available/rvantonderTailoring

- @rvantonder, rvantonder@gmail.com, Rijnard van Tonder (corresponding author)
- @clegoues, clegoues@cs.cmu.edu, Claire Le Goues

# wants Available badge

**Comment by timm** [comment]
@grumpyreviewer and @unknown-user1234 : I look forward to your reviews.

**Comment by unknown-user1234** [comment]
The authors applied for the **Available** badge.

The installation of the artifact was successful and the provided documentation on how to run the experiments was satisfactory. I suggest an edition in the readme.md to correct the script files names (e.g., change ./php-run.sh for ./run-php.sh). The remainder of the submission is ok according to the Available badge specifications. 

Decision: **Accept**

**Comment by timm** [comment]
So we are at badge=available and awaitg @grumpyreviewer 's veto or confirmation

**Comment by grumpyreviewer** [comment]
Confirmed  _available_.

I can also install the artifacts and the commands to run the experiments are clear. Took a while to download the vm from zenodo, but that worked too. It may be worth adding the readme to the zenodo submission alongside the vm, in case of future changes to the github repo

**Comment by minkull** [comment]
Both reviewers recommend available.

**Comment by rvantonder** [comment]
Thank you reviewers! We'll take care to update the README for accuracy and include it in the Zenodo submission. Apologies for the big VM, it was the most straightforward option.
