### ISSUE TITLE
SLEMI tool to automatically find compiler bugs in Simulink

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#122]
https://github.com/researchart/rose6icse/tree/master/submissions/available/shafiulSLEMI
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/shafiulSLEMI

- Shafiul Azam Chowdhury (corresponding author). GitHub handle: @shafiul. Email (remove nospam): shafiulazam dot chowdhury at mavs dot nospam uta dot edu
- Sohil Lal Shrestha. GitHub handle: 50417. Email: sohil dot shrestha at mavs dot nospam dot uta dot edu
- Taylor T. Johnson. GitHub handle: ttj. Email: taylor dot johnson at vanderbilt nospam dot edu
- Christoph Csallner. GitHub handle: csallner. Email: csallner at uta nospam dot edu

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by anonymous042** [comment]
* LICENSE.md: OK
* CONTACT.md: OK

This artifact is a tool to automatically find compiler bugs in Simulink. The main artifact is at https://zenodo.org/record/3627640, it contains 217 Matlab files totaling 11000 lines, the main file is https://github.com/shafiul/slemi/blob/master/covcfg.m. A data file is available in `./reproduce/samplecorpus`
 
While the artifact is available, the main problem is that it depends on proprietary software (Matlab) and proprietary data formats (eg `*.mat`). I think that open science requires open execution environments (not Matlab) as well as open and documented data formats.

**Comment by timm** [comment]
I'm going to make an executive decision and allow Matlab as a tool for open science. Many universities offer free licenses to students for that tool). No, its not ideal but you gotta bend some rules in order to build a tent (but note to @shafiul: take care in future; try to avoid Matlab, else face  @anonymous042 's opinion once again)

@data-track-reviewer : I look forward to your review.

**Comment by ghost** [comment]
With this executive decision, I am leaning to follow the authors in their argumentation for reusable and available badges. I appreciate that a DOI is provided, especially since it is complemented by a github page. The video is a nice touch.
