### ISSUE TITLE
tdurieux

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#124]
https://github.com/researchart/rose6icse/tree/master/submissions/available/tdurieux
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/tdurieux

1. thomas@durieux.me, tdurieux, corresponding author.
2. joao@joaoff.com, jff, corresponding author.
3. rui@computer.org, ruimaranhao, corresponding author.
4. pedrocrvz@gmail.com, pedrocrvz, corresponding author.

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by sec365** [comment]
The authors apply for the available and reusable badges.

====available====
I first checked the dataset SB curated. It contains 69 solidity smart contracts, of which the vulnerable lines are clearly listed. The explanation of each vulnerability type is taken from https://dasp.co/. I believe this dataset, although small in scale, is useful for future research.

I then checked the dataset SB wild, which is much larger in scale than SB curated. This dataset has no useful annotations such as vulnerable lines, but still, I believe it is also useful for future research.

**So, I recommend the “available” badge.** 

One minor suggestion is to put the artifacts on Zenodo (or similar services) and provide a DOI.

====reusable====
The installation of the tool is very easy. I tried the examples provided by the authors. Everything worked well.
I then tried the framework on several solidity smart contracts written by myself and some collected from https://github.com/crytic/not-so-smart-contracts.git. Again, the framework worked very well, and the analysis results are clearly summarized in JSON files.

**So, I also recommend the “reusable” badge.**

**Comment by timm** [comment]
@andromeda04 : I look forward to your review.

**Comment by andromeda04** [comment]
The authors apply for the "Reusable" and “Available” badges

- **Reusable**: The data and SmartBugs tool are straightforward and work as expected. First, I could successfully install the tool after having Docker and Python installed. Then, I successfully used the tool on several solidity smart contracts available in the provided dataset. 

Some minor comments/suggestions from reviewer: the authors might consider adding the instructions to install Docker and Python to the file INSTALL.md

- **Available**: Both the dataset of 47,518 smart-contact extracted from the Ethereum network and the SmartBugs execution framework are available on Github. Also, the raw results of vulnerability analysis are also available on the same Github folder. 


**Recommendation**: I recommend both badges for this paper.
