### ISSUE TITLE
oss-donations

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#133]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/oss-donations

# Contact Lists

- Cassandra Overney (*corresponding author*)
  - Email: coverney@olin.edu
  - Github id: [coverney](https://github.com/coverney)

- Bogdan Vasilescu
  - Email: vasilescu@cmu.edu
  - Github id: [bvasiles](https://github.com/bvasiles)

# Authors

```tex
 \author{Cassandra Overney}
 \affiliation{%
  \institution{Olin College, USA}}
  \email{coverney@olin.edu}

 \author{Jens Meinicke}
 \affiliation{%
  \institution{Carnegie Mellon University, USA}}
  \email{jensm@andrew.cmu.edu}

 \author{Christian KÃ€stner}
 \affiliation{%
  \institution{Carnegie Mellon University, USA}}
  \email{kaestner@cs.cmu.edu}

 \author{Bogdan Vasilescu}
 \affiliation{%
  \institution{Carnegie Mellon University, USA}}
  \email{vasilescu@cmu.edu}

```

# applying for available

**Comment by happyanonymous** [comment]
As of now, I am not sure if the artifact is *Available*
I had problems following the instructions. Although I successfully set up the environment (see below):

![image](https://user-images.githubusercontent.com/44096371/74385621-d2dcdd80-4e58-11ea-8005-25f090b97809.png)

I had problems accessing the url (see below)

![image](https://user-images.githubusercontent.com/44096371/74385653-ec7e2500-4e58-11ea-9cfa-bdada31f9bca.png)

I'm using a machine with Windows 10 installed.
I'm using the Docker ToolBox.

**Comment by icse-2020-reviewer** [comment]
*Reusable:
The structure of the data is explained and documented. The artifacts the authors provide are available on our environment. We can obtain the outputs from four Jupiter Notebook files and one Rmd file. 

The environments are following:
- MacOS Catalina version 10.15.2
- Docker version 19.03.5, build 633a0ea

**Comment by danielcalencar** [comment]
Just wanted to specify that my Docker toolbox version is:

Docker version 18.03.0-ce, build 0520e24302

**Comment by happyanonymous** [comment]
I installed an Oracle VM with linux and could obtain the same results as @icse-2020-reviewer. I am happy to recommend the *Reusable* badge

**Comment by timm** [comment]
@coverney   @bvasiles 

- your status.md file says "we want available"
- your files are in "reusable" directory 
- reviewers are happy with "reusable"

can I infer a typo in your status.md? can I assign this the "reusable" badge?

**Comment by coverney** [comment]
@timm we meant to apply for the reusable badge. Thank you very much!

**Comment by bvasiles** [comment]
@minkull @timm Thanks for the "reusable" badge. 

We were a little confused earlier about the possibility of applying for multiple badges based on the instructions on the [ICSE website](https://conf.researchr.org/track/icse-2020/icse-2020-Artifact-Evaluation#Call-for-Submissions):

> If those artifact(s) are accepted, they will each receive one (and only one) of the badges below on the front page of the authors’ paper and in the proceedings

But it seems that some authors have been asking for (and receiving) multiple badges. 
Our intention was actually also to request "available" + "reusable". I believe we qualify for "available" too, as our repo is indexed by Zenodo: https://doi.org/10.5281/zenodo.3674277 
(note: Zenodo was down right before we applied for the artifact eval, so we added the DOI later)

Would you consider assigning "available" as well? Many thanks.

**Comment by bvasiles** [comment]
@timm @minkull Friendly ping on the above. Thanks
