### ISSUE TITLE
society-oriented-applications-development

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#135]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/society-oriented-applications-development

## **Contact information**

- Rifat Ara Shams (rifat.shams@monash.edu) -- Corresponding Author
- Waqar Hussain (waqar.hussain@monash.edu)
- Gillian Oliver (gillian.oliver@monash.edu)
- Arif Nurwidyantoro (arif.nurwidyantoro@monash.edu)
- Harsha Perera (harsha.perera@monash.edu)
- Jon Whittle (jon.whittle@monash.edu)

## **GitHub Id**

[https://github.com/salehmasum](https://github.com/salehmasum)

# applying for "reusable"

**Comment by minkull** [comment]
@salehmasum Missing INSTALL.md file. Could you add asap

**Comment by minkull** [comment]
@salehmasum Missing INSTALL.md file. Could you add asap

**Comment by timm** [comment]
waiting for a new pull request on this one...

**Comment by salehmasum** [comment]
@minkull @timm just added the INSTALL.md file. Extremely sorry for the very unexpected delay. For any additional information / file please don't hesitate to let me know. Thank you.

**Comment by artifacts-reviewer** [comment]
I have two suggestions for improvement.

1. The README file contains many "&#39" instead of an apostrophe. This should be fixed.
2. The README file makes it seem that the csv will contain only y/n for the value columns. However, the columns contain the actual labelled values as well. This should be further clarified.

**Comment by anonreporev** [comment]
I have further suggestions/clarifications.

The readme files contains several characters like "&#39" I guess this is an error.

In the readme, it says:  "if there are any irrelevant and meaningless reviews. We found 119 irrelevant and meaningless reviews and removed those reviews manually." In terms of artefact re-use it may have been nice to leave those in, especially the irrelevant reviews, as they may be relevant for other studies.   Unless this process is very clear and repeatable.

I agree with point 2 of the other reviewer, the readme makes it sound like only yes/no was provided, when actually the specific value was listed.

I think the readme should mention language: what languages are in the data set?  Are there more than one?  One languages must one be able to read to use the data set?

Why are there many repeated reviews?  For example, line 191-195 "	weather news is very good" repeated.  If someone were to re-use this data set, how should they treat repeated reviews like this?

Thank you.

**Comment by timm** [comment]
@salehmasum : thank you for submitting to ICSE'20.

please make a pull request with the above changes. then we can check if that moves our reviewers to move to completion .

**Comment by salehmasum** [comment]
I have addressed all the comments from the reviewers. Please let me know for any additional information. Thank you.

**Comment by timm** [comment]
@artifacts-reviewer @anonreporev 

please confirm: do we have enough to badge this as "reusable"?

**Comment by artifacts-reviewer** [comment]
I am happy with awarding this badge. Thanks to the authors for making the updates.

**Comment by anonreporev** [comment]
I agree.  Thanks.

**Comment by salehmasum** [comment]
Thanks.

**Comment by minkull** [comment]
Both reviewers recommend reusable.
