### ISSUE TITLE
catolino

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#137]
https://github.com/researchart/rose6icse/tree/master/submissions/available/catolino
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/catolino

# CONTACT

1. Gemma Catolino (corresponding author):
	* email: gcatolino@unisa.it
	* GitHub ID: gcatolino

2. Fabio Palomba:
	* email: fpalomba@unisa.it
	* GitHub ID: fpalomba

3. Damian Andrew Tamburii:
	* email: d.a.tamburri@tue.nl
	* GitHub ID: maelstromdat

4. Alexander Serebrenik:
	* email: a.serebrenik@tue.nl
	* GitHub ID: aserebrenik
	
5. Filomena Ferrucci:
	* email: fferrucci@unisa.it
	* GitHub ID: -

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by icse-2020-reviewer** [comment]
*Reusable:
The structure of the data is explained and documented. All four files can be opened and are very valuable for other researchers in this domain. 

*Available
Archival repository/DOI: The replication package is uploaded into Figshare and has https://doi.org/10.6084/m9.figshare.10075406.v6 as a link to this repository along with a unique identifier for the object.

**Comment by danielcalencar** [comment]
I agree with the previous reviewer:

*Reusable:
All the artifacts are very well described and all the procedures that were used to come up with the artifacts are also described.

*Available
As previously noted the replication package is available on Figshare with a unique identifier.

**Comment by timm** [comment]
👍
