### ISSUE TITLE
bug_fixing_

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#152]
[https://github.com/researchart/rose6icse/tree/master/submissions/replicated/bug_fixing_](https://github.com/researchart/rose6icse/tree/master/submissions/replicated/bug_fixing_)

Replicated study:
Predicting bug-fixing time: A replication study using an open source software project (link)
Shirin Akbarinasaji* Bora Caglayan Ayşe Başar
corresponding author, GitHub ID: @ShirinAkbari;

Original paper:
Predicting Bug-Fixing Time: An Empirical Study of Commercial Software Projects (link)
Hongyu Zhang, Liang Gong, Steve Versteeg, Jue Wang, Zeqi Shen, and Janine Radford

# applying for replicated

**Comment by artifact-review** [comment]
The author apply for "Replicated" badge.

+ **Avalable**: The data from original paper comes from private software project that is not publicly available. In the replicating study, in constrast, the authors collected data for an open source system (Mozilla Firefox) from public issue tracking system (Bugzilla). In addition, the reviewer could not find the Firefox dataset from the paper, therefore, we have to reject the "Available" badge"

+ **Replicated**: As the presiquisite "Available" criteria could not be verified, we would have to reject the "Replicated" badge as well. Even though the Firefox data is publicly published, it is difficult to justify if the results from original paper have been successfully replicated given the fact that the authors used different dataset

**Decision:** Rejected

**Comment by unknown-user1234** [comment]
I am having a problem in reviewing this artifact. The github repository "https://github.com/researchart/rose6icse/tree/master/submissions/replicated/bug_fixing_" does not contain the software artifacts. Could someone please show me the correct repository?

**Comment by timm** [comment]
@unknown-user1234 so, as of know, like @artifact-review , you would gave to reject "replicated" since the material is not "available"?

**Comment by unknown-user1234** [comment]
Thank you @timm !!

I misread the @artifact-review comment. 

As the material is not **available** (which is a constraint for the replicated badge), I recommend to reject the **replicated** badge to this artifact submission.

Decision: **Reject**

**Comment by artifact-review** [comment]
@unknown-user1234 @timm The repo URL misses an underscore at the end due to GitHub markdown's url auto-correction. The correct repo is located [here](https://github.com/researchart/rose6icse/tree/master/submissions/replicated/bug_fixing_) if you would like to checkout the repo.

**Comment by timm** [comment]
I can see that this paper does a "replication" w.r.t. the standards of say, EMSE.

but not to the standards required by the ACM badges.

this is a quandary. Will discuss with @minkull

**Comment by timm** [comment]
Our CFP says

"For Replicated and Reproduced Badges
For “replicated” and “reproduced” badges, authors will need to offer appropriate documentation that their artifacts have reached that stage."

so that imples replicated has to need available

can the material to support this artifact?

otherwise, no badge

**Comment by minkull** [comment]
Many thanks all for your inputs.

No badge awaded.
