### ISSUE TITLE
Johnson-CausalTesting

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#165]
https://github.com/researchart/rose6icse/tree/master/submissions/available/Johnson-CausalTesting

**Brittany Johnson** (corresponding author)

*email*: bjohnson@cs.umass.edu

*github id*: brittjay0104

**Yuriy Brun**

*email*: brun@cs.umass.edu

*github id*: brunyuriy

**Alexandra Meliou**

*email*: ameli@cs.umass.edu

*github id*: ameliou

@brittjay0104 under review

# they seek the  "available" badge

**Comment by azhe825** [comment]
@brittjay0104 @timm
 - Reusable passed.
 - For available, currently, this is on github repo and google drive. It is suggested to get a DOI or a permanent link for the code. E.g. at [zenodo.org](https://zenodo.org/) you can (1) release one version of your repo, then (2) upload that zip file to zenodo for a DOI.

**Comment by arennax** [comment]
Available tests passed (macOS Catalina 10.15.3, VirtualBox 6.1), the source can be accessed on github repo and google drive.

**Comment by brunyuriy** [comment]
We have created a release with a DOI via zenodo.org:
doi: 10.5281/zenodo.3676139
https://doi.org/10.5281/zenodo.3676139

**Comment by azhe825** [comment]
@brunyuriy @timm 
Reusable and Available passed.
