### ISSUE TITLE
recheck

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#17]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/rlcheck

Contact:

- Sameer Reddy
email: sameer.reddy@berkeley.edu
github: sameerreddy13
- Caroline Lemieux (corresponding author):
email: clemieux@cs.berkeley.edu
github: carolemieux
- Rohan Padhye
email: rohanpadhye@cs.berkeley.edu
github: rohanpadhye
- Koushik Sen
email: ksen@cs.berkeley.edu
github: ksen007

# applying for  reusable/available  .

**Comment by unknown-user1234** [comment]
The authors applied for the reusable badge:

This badge depends on the available badge. Indeed, the artifact is available and well documented. Based on this documentation, it was possible to properly run the commands necessary to generate the results present in the paper. Moreover, the navigation through the code is easy and reusing the code in different data doesn't seem to be a problem. 

Decision: **Accept**

**Comment by minkull** [comment]
@grumpyreviewer look forward to your review

**Comment by grumpyreviewer** [comment]
I managed to follow all the steps documented by the authors. Everything worked.

However, the artifact comes *only* as a docker image. My interpretation of functional is that the artifact itself (i.e., rlcheck) should be available for download and installation, independently of the docker image, which contains a copy of it. (I checked on the jqf repo but could not find the RL examples there).

@minkull : if distribution of the artifact only in the form of a docker is fine, the code examples together with the provided documentation would be enough for the _reusable_ badge, imo.

**Comment by timm** [comment]
@sameerreddy13
@carolemieux
@rohanpadhye
@ ksen007  

we cannot badge unless you give us source code access. 

please send a pull request with details on that access post a link to the relevant files here in this issue

if you do that, u will get reusable and available

**Comment by carolemieux** [comment]
The source code is available at: https://github.com/sameerreddy13/rlcheck

I've created a pull request with these details here:
https://github.com/researchart/rose6icse/pull/201

The modifications to README.md are:
https://github.com/researchart/rose6icse/pull/201/commits/995677081c8e1153a58c27ea1cd5efe16c5cd5d0
The modifications to INSTALL.md are:
https://github.com/researchart/rose6icse/pull/201/commits/996cf6d464ae2b9c45291519f1789c6a3289fb54

**Comment by timm** [comment]
With the source code link added, I am willing to declare reusable and available

Unless @grumpyreviewer or @unknown-user1234 want to veto that. 

Please advise.

**Comment by unknown-user1234** [comment]
I agree, @timm. I interpreted the docker image as a more difficult, but not impossible way to download the code. Therefore, I keep the acceptance of both badges, available and reusable.

**Comment by minkull** [comment]
Available and reusable awarded.
