### ISSUE TITLE
zhenbang

### ISSUE THREAD

**Issue by arennax** [researchart/rose6icse#189]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/zhenbang

- Zhenbang Chen
  - email: zbchen75@gmail.com
  - github id: [zbchen](https://github.com/zbchen)

# applying for AVAILABLE and  REUSABLE

**Comment by arennax** [comment]
@zbchen @timm 

 - available and reusable tests are passed (macOS Catalina 10.15.3, Docker version 19.03.5)
 - demo program running successfully (test.bc, demo.bc), expected output achieved
 - the result of one verification task is reproduced
 - there are some minor typos in INSTALL.md: verifcation --> verification, etc..

**Comment by azhe825** [comment]
@timm @zbchen 
Reusable and Available passed.
