### ISSUE TITLE
Fax

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#25]
https://github.com/researchart/rose6icse/tree/master/submissions/available/Fax

- Jiwei Yan (corresponding author), Email: yanjw@ios.ac.cn, Github id: hanada31 (https://github.com/hanada31)
- Hao Liu, Email: lansedeyu94@live.com, Github id: AssassinRain (https://github.com/AssassinRain)

**Comment by dmz-peerreview** [comment]
Dear authors, 

Thanks for your submission. Overall, I had major difficulties and have to raise the following concerns:

* the pasted text for the license model (Apache) seems to be strange and copied 1:1 without proper adoption, please check,
* required OS, Java or Ant version is not specified, 
* I couldn't find any binaries,
* the tool uses already deprecated functionality (`android create project`) without explaining how to find, install, and use this older version,
* A Z3 lib dependency is required without linking to the project (I assume it is https://github.com/Z3Prover/z3) and documenting its installation, usage, and the used version,
* I assume that *Prepare Android environment* refers to https://source.android.com/setup/build/initializing, but it is not documented, and
* I highly recommend to use docker. 

Please note that I don't have an Android smartphone at hand, so I cannot use Fax. 

I was not able to run the code with the given instructions only and within a reasonable time. The documentation seems to me rather superficial with a insufficiently precise speficition of requirements and versions, and it does appears not to include all necessary information itself nor the references to it. 

As it stands, the package is currently not functional.

**Comment by timm** [comment]
@AnAnonymousReviewer  : I look forward to your review.

**Comment by AnAnonymousReviewer** [comment]
Dear authors,

it appears that the artifacts are consistently and completely stored in a publicly accessible archive repository. However, with the given documentation I was not able to execute these. I followed the instructions in [README.md](https://github.com/hanada31/Fax/blob/master/README.md) and [INSTALL.md](https://github.com/researchart/rose6icse/blob/master/submissions/available/Fax/INSTALL.md), but encountered several problems:


1. Versions
    1. Neither in these md-files nor in the publication there are notes for the operating system or the Ant version. 
        1. For the review, I worked with macOS 10.11.6 and Ant 1.9.14.
    1. The Java version can only be taken indirectly from the corresponding publication.
        1. For the review, Java 8 was used.

1. Android environment
    1. There are no direct instructions how to set up this Android environment and what is needed besides the Android SDK tools.
    1. For the version of the Android SDK Tools only an upper but no lower version is given.
    1. There are no direct references to the version of Android Studio and whether it is needed at all besides the Android SDK tools.
    1. The version of the Android platform can only be taken indirectly from the corresponding publication.
    1. For the review, Android Studio 3.5.3 was installed with the Android SDK Tools 25.0.0 and Android 8.0 version as described.

1. Z3 Theorem Prover
    1. The documentation specifies that Fax requires the Z3 dynamic link library and the dynamic link library for the Z3 Java API, but no direct dependency on the Z3 Theorem Prover is described.
    1. Although the two files were added to the java library path in /etc/profile according to the instructions, a Java exception occurred when executing [runFax.sh](https://github.com/hanada31/Fax/blob/master/FaxTool/runFax.sh).
        1. ```java
            Exception in thread "main" java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
                at java.lang.Runtime.loadLibrary0(Runtime.java:871)
                at java.lang.System.loadLibrary(System.java:1124)
                at com.microsoft.z3.Native.<clinit>(Native.java:14)
                at com.microsoft.z3.Context.<init>(Context.java:73)
                at solver.ConstrainSolver.checkSatisfiablity(ConstrainSolver.java:38)
                at solver.ConstrainSolver.eliminateConfictedPaths(ConstrainSolver.java:22)
                at generator.ICCGenerator.generateAUPs(ICCGenerator.java:73)
                at generator.ICCGenerator.generate(ICCGenerator.java:50)
                at main.Main.analyzeSingleApk(Main.java:182)
                at main.Main.start(Main.java:126)
                at main.Main.main(Main.java:43)
            ```

1. Android device
    1. An Android device with allowed "USB debugging" was connected, but due to the errors that occurred, the appropriate evidence of verification and validation cannot be evaluated.
    1. In the documentation and the publication the necessary information and/or references to how and with which parameters an Android emulator should be set up were missing.

1. Licensing model
    1. The attached [LICENSE.md](https://github.com/researchart/rose6icse/blob/master/submissions/available/Fax/LICENSE.md) file contains the Apache License version 2.0, but it does not describe the distribution rights of the artifacts in the archive repository.
    1. No license is stored on the actual archive repository.
    1. It is not clear under which license the dynamic link library for Z3 is licensed.

Due to the lack of specification of the system environment, the artifacts cannot be executed without errors according to the current status.

**Comment by JonDoe-ArtifactsTrack** [comment]
Dear authors,
Thanks for your submission. I have followed your instructions carefully but i could not execute all your experiments. For the review have used the following settings. Also, note that you have missed some information about the versions needed for some of the tools.
Settings:
-OS:
 Os Used: WIn 10 Home
	 Os Specified: N/A
-SDK:
SDK Tools Specified: Lower than 25.2.3
	SDK Tools Used: 25.2.2
-Platform-Tools:
	
Platform-Tools Specified: N/A
	Platform-Tools Used: 29.0.5
			          26.0.0
			          25.0.1
			          25.0.0
-Java:
Java Version Specified: N/A
	Java Version Used: 1.8.80
-Ant:
Ant Version Specified: N/A
	Ant Version Used: 1.10.7
-Android Studio:
Android Studio Version Specified: N/A
	Android Studio Version Used: 2.3.2
	
Using these settings i could run your project on an Android device with API Level 17 and Android 4.2 (Google Api), but only the Preprocess Phase terminated successfully. 
After the Preprocess phase i got this error: IndexError: list index out of range.
Below is the log i got:

PS D:\Fax-master\Fax-master\FaxTool> .\runFax.bat
D:\Fax-master\Fax-master\FaxTool>C:\Users\Dario\AppData\Local\Programs\Python\Python27\python.exe D:\Fax-master\Fax-master\FaxTool\script\run.py
CSipSimple.apk
[100%] /data/local/tmp/CSipSimple_ins.apk
Error: Unknown option: -g
Preprocess Finish!
apk\
CSipSimple.apk has been analyzed. To analyze again, modify Result_testGen\history.txt
Preprocess Finish!
com.csipsimple
com.csipsimple not install
execute  adb install Result_testGen\testcases\CSipSimple\apkTestCases\test.apk
[100%] /data/local/tmp/test.apk
    	pkg: /data/local/tmp/test.apk
Failure [INSTALL_FAILED_ALREADY_EXISTS]
execute  adb shell input keyevent 4
execute  adb shell input keyevent 4
execute  adb logcat -c
execute  adb shell am start -n fax.com.csipsimple/.Activity_1 >> Result_launch\Logs\CSipSimple\turn_0\/1_com.csipsimple.ui.prefs.hc.MainPrefs.cmdinfo
Traceback (most recent call last):
  File "D:\Fax-master\Fax-master\FaxTool\script\run.py", line 38, in <module>
	launcher.launchAct()
  File "D:\Fax-master\Fax-master\FaxTool\script\LaunchActs.py", line 31, in launchAct
	self.testAPK( folder , pkgName, fn)
  File "D:\Fax-master\Fax-master\FaxTool\script\LaunchActs.py", line 69, in testAPK
	self.compareActivity(line.split("\t")[1], fn + "\t" +str(id), package)
  File "D:\Fax-master\Fax-master\FaxTool\script\LaunchActs.py", line 90, in compareActivity
	current = line.split(" ")[7].split("/")[1]
IndexError: list index out of range

Furthermore, on the Android Device: Unfortunately, CSipSimple_Launcher stopped.

Note that the SDK-Tools version. 25.2.2 are not available from the official site.

**Comment by timm** [comment]
we can do available without it being executable

- @JonDoe-icse20Artifacts  reports they can find the files, but they won't run
- @AnAnonymousReviewer  reports the same thing

if they won't run for platform reasons and if we believe that on ANOTHER platform they might run they we can do "Available"

but if it looks like the artifact is incomplete and not runable anywhere then we must do no badge.

- @JonDoe-icse20Artifacts @AnAnonymousReviewer  please advise

**Comment by AnAnonymousReviewer** [comment]
Dear @timm, 

actually I disagree: "Available" has "functional" as a precondition (https://conf.researchr.org/track/icse-2020/icse-2020-Artifact-Evaluation#Call-for-Submissions), and in "functional" one of the criteria is "exercisable". If we stick to the description at https://www.acm.org/publications/policies/artifact-review-badging for the criteria, then "exercisable" means "Included scripts and/or software used to generate the results in the associated paper can be successfully executed, and included data can be accessed and appropriately manipulated" (emphasis on "can be successfully executed"). 

I am all fine to change the criteria for ICSE, but then we should change them on the webpage and for all submissons. Additionally, I think that "data [...] can be appropriately manipulated" may be too much to ask. 

Note that the original ACM "available" badge does not have functional as a precondition. So maybe the best would be to indeed change the description at https://conf.researchr.org/track/icse-2020/icse-2020-Artifact-Evaluation#Call-for-Submissions and remove that precondition from "available". 

Probably this is why "functional" is a wortwhile additional badge to have on its own. It seems to be more difficult to achieve than "available" (in the ACM sense) in my opinion (taking into account the experience with this year's artifacts).

Regarding this submission and with the current interpretations, I agree to award no badge. 

Best regards
AnAnonymousReviewer

**Comment by timm** [comment]
@AnAnonymousReviewer 
I hear your objection. I thank you for the care of your analysis. I have several comments

-  for icse'20, we have constantly applied "available" does not mean executable (if there is evidence that on SOME platform, if not perhaps on the reviewer's machine)  
-  the PLDI people also declare that "available" not necessarily mean executable. so we are consists with practice at leading conferences. 
- as to changing the CFP, I agree that that is desirable. but too late for icse'20. 
   - but fyi, that change (that available does not necessity need available) is currently  propagate  across to FSE,ASEm etc (i.e. all the venues doing artifacts in 2020). 

in any case,  my summary of the above is we have enough info right now to  badge for "available". but I will review this case with @minkull before making a final decision

**Comment by minkull** [comment]
Many thanks all for the discussions!

Available badge awarded.
