### ISSUE TITLE
shangwenRepairThemAll

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#6]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/shangwen

Authors:
- Kui Liu (email: kui.liu@uni.lu, GitHub id: @BruceKuiLiu 
- Shangwen Wang (email: wangshangwen13@nudt.edu.cn, GitHub id: @ShangwenWang

# Seeking "reusable"

**Comment by timm** [comment]
@ShangwenWang
I want to   delete the directories Patches and Execution Logs- makes it easier for others to check out this repo and add these submission. 

ok for me to do that?

**Comment by timm** [comment]
@ShangwenWang
I went ahead and deleted the directories Patches and Execution Logs 

let me know if I need to restore them

**Comment by ShangwenWang** [comment]
@timm Ok, you can change the organization as you like.

**Comment by ShangwenWang** [comment]
@timm Sorry, I think I misunderstand your meaning before.
The two directories cannot be deleted since all the useful data are stored in them.
Please recover them or the reviewers cannot get practical information.

**Comment by ShangwenWang** [comment]
@timm Another way is to guide the reviewers to refer the repo https://github.com/ShangwenWang/rose6icse/tree/master/submissions/reusable/shangwen if you could not add the data.
All the data is in that repository as well.

**Comment by artifacts-reviewer** [comment]
The GitHub repository contains a large amount of data: patches and execution logs from 16 open-source automated program repair systems (only 10 produce logs) using two different fault localization settings. This data makes a nice addition to the publication.

Some comments:
1) The install.md file should more clearly explain that there are no installs required for this dataset and that the links provided are all external tools that were used to create the dataset.

2) There are some typos in the README file:
"BugID is the bug ids of the related Defects4J bugs, e.g., Chart-1)" is missing an "("
"Number1 is the number of patches, that can pass the compiling process successfully," should be Number2
"there are 116 patch candidates are generated" only the first "are" is needed

3) Finally, it would also be useful to explain how the logs can be mapped to the patches as the naming of the log files is not the same as the patch files.

**Comment by ShangwenWang** [comment]
@timm @artifacts-reviewer 
Thanks for the valuable comments.
We have made modifications based on the comments in both our forked repository (https://github.com/ShangwenWang/rose6icse) and the repository referred in our paper (https://github.com/APRStudy/APRStudy).

**Comment by artifacts-reviewer** [comment]
@ShangwenWang please push your commits to the repos as I cannot see your updates.

@timm @minkull this issue needs another reviewer

**Comment by Kaka727** [comment]
@artifacts-reviewer Hi, updates have been already made.
Thanks

**Comment by artifacts-reviewer** [comment]
<img width="1023" alt="Screen Shot 2020-02-15 at 2 05 19 PM" src="https://user-images.githubusercontent.com/50120191/74578945-5c78e080-4ffc-11ea-8a7f-4126c41354ef.png">

The repo has not been updated since last month, see screenshot above.

**Comment by ShangwenWang** [comment]
@timm Please merge our pull request #167

**Comment by ShangwenWang** [comment]
@timm We have created a new pull request #168 deleting the patches and logs.
You can merge it without concerning breaking the organization.
Thanks~

**Comment by ShangwenWang** [comment]
@artifacts-reviewer The chair has not accepted our Pull Request.
I guess you can refer to our own repo: https://github.com/APRStudy/APRStudy or our folked repo: https://github.com/ShangwenWang/rose6icse .
Updates have been already made in both repositories.
Many thanks~

**Comment by artifacts-reviewer** [comment]
The updates look good to me. 

I suggest the files be placed in an online archive like Zenodo or Figshare and the DOI shared.

**Comment by ShangwenWang** [comment]
@artifacts-reviewer  We have uploaded it to Figshare (DOI: https://doi.org/10.6084/m9.figshare.11859954.v1).
Please have a check

**Comment by timm** [comment]
dear @ShangwenWang , thank you so much for your responsiveness.  and apologies for my own tardiness.

@artifacts-reviewer :please confirm your current views on assigning the "reusable" badge. should we require more stuff from @ShangwenWang ?

**Comment by artifacts-reviewer** [comment]
I am happy with the artifacts for the reusable badge, and I also believe the available badge could be awarded.

**Comment by minkull** [comment]
@icse-artifact-reviewer please could you provide a review for this artifact?

**Comment by timm** [comment]
@icse-artifact-reviewer 
currently, this one will get available and reusable

please contribute your confirmation or veto of that decision

**Comment by icse-artifact-reviewer** [comment]
Dear Authors,

The repository has indeed provided a large amount of data for potential reuse, supported with good documentation. One minor issue is that, the DOI does not seem to have been mentioned anywhere on the repository or have I missed anything? It should be placed in the readme.md

Otherwise, I recommend **Available + Reusable**

**Comment by minkull** [comment]
@BruceKuiLiu please could you confirm the DOI?

**Comment by Kui-Liu** [comment]
@minkull We created a new DOI (http://doi.org/10.5281/zenodo.3678960) with zenodo. The DOI is confirmed and has been added the repository. Thanks.
