### ISSUE TITLE
CPC

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#95]
https://github.com/researchart/rose6icse/tree/master/submissions/available/CPC

| Corresponding | Name          | ID        | Email                  |
| ------------- | ------------- | --------- | ---------------------- |
|               | Juan Zhai     | Katie2018 | zhai17@purdue.edu      |
| Yes           | Xiangzhe Xu   | XZ-X      | xxz@smail.nju.edu.cn   |
|               | Yu Shi        |           | shi442@purdue.edu      |
|               | Guanhong Tao  |           | taog@purdue.edu        |
|               | Minxue Pan    | minxuepan | mxp@nju.edu.cn         |
|               | Shiqing Ma    |           | shiqing.ma@rutgers.edu |
|               | Lei Xu        |           | xlei@nju.edu.cn        |
|               | Weifeng Zhang |           | zhangwf@njupt.edu.cn   |
|               | Lin Tan       |           | lintan@purdue.edu      |
|               | Xiangyu Zhang |           | xyzhang@cs.purdue.edu  |

# applying for the Available Badge

**Comment by anonymous-002** [comment]
Thanks for submitting your artifacts. I followed your instructions to download and run your Docker image, but to my surprise the `start.sh` script executed in less than a second (you mention that it should take 2 hours in the `install.md` file). Then, I looked into the `result` directory and the results were there. I emptied the `result` director, ran the script again, and the results were created again.

Surprised by the fast execution, I looked into the `start.sh` script and found that it only copies the results from elsewhere to the `result` directory.

```bash
~ % cat start.sh
#!/bin/bash
cd how-it-is-done
#./propagate.sh
cd ..
mkdir -p result
cp how-it-is-done/*.xlsx result/
cd CPC-what-property
#./run.sh
cd ..
cp CPC-what-property/n_distance_uniq.csv result/what-property-result.csv
```

I found the `propagate.sh` script mentioned in a comment above in the `how-it-is-done` directory, but it only outputs some code.

```
how-it-is-done % ./propagate.sh 
./CommentCollection/src:./::./CommentCollection/lib/*:./CommentCollection/lib/poi-lib/*
Receiving 3 arguments.
/root/how-it-is-done/Nicad_input/input_apachedb/ + 
/root/how-it-is-done/Nicad_input/input_apachedb/ + apachedb/
/root/how-it-is-done/Nicad_input/input_apachedb/ + apachedb/bin/
/root/how-it-is-done/Nicad_input/input_apachedb/ + apachedb/bin/templates/
/root/how-it-is-done/Nicad_input/input_apachedb/ + apachedb/tools/
/root/how-it-is-done/Nicad_input/input_apachedb/ + apachedb/tools/javadoc/
/root/how-it-is-done/Nicad_input/input_apachedb/ + apachedb/tools/javadoc/logo/
/root/how-it-is-done/Nicad_input/input_apachedb/ + apachedb/tools/l10n/
/*
   Derby - Class LocCompare

   Licensed to the Apache Software Foundation (ASF) under one or more
   ...
 */


import java.io.*;
import java.util.ArrayList;
```

I am at a loss here. You have results, but the script that should produce these results outputs apparently unrelated source code. 

Please, clarify how your artifacts are supposed to be used.

**Comment by XZ-X** [comment]
Sorry, I made a silly mistake. I tried to test whether the start script runs well, so I just commented out two commands: `./run.sh` and `./propagate.sh`, respectively. I've updated the docker image. Also, if you don't want to pull the image again, you could just un-comment that two commands from the `start.sh`. 
Then it should look like:
```bash

#!/bin/bash
cd how-it-is-done
./propagate.sh
cd ..
mkdir -p result
cp how-it-is-done/*.xlsx result/
cd CPC-what-property
./run.sh
cd ..
cp CPC-what-property/n_distance_uniq.csv result/what-property-result.csv

```

Sorry again for the inconvenience. 


> I found the `propagate.sh` script mentioned in a comment above in the `how-it-is-done` directory, but it only outputs some code.
                                                                                                                                                                                                                                                                                                                                                                                 
By the way, `propagate.sh` generates the excels, and output some source code in the meantime. Please just ignore those source code in the stdout. They're for debugging usage.

Thank you so much for pointing this out!

**Comment by anonymous-002** [comment]
No problem at all. I only noticed that the `propagate.sh` script was still running after I wrote the comment above. Now I understand that it will produce the Excel files when it finishes. Maybe you could add that information to the `install.md` file in your repository. By the way, any chance of providing an instance or something that runs in a few minutes instead of a couple of hours?

**Comment by XZ-X** [comment]
Thank you for your suggestion. A pull request has been sent about `install.md`. 

Sorry about the couple-hours run time. We don't have a short instance now. We will add a user-friendly case in the future. For now, if the `propagate.sh` and `run.sh` could start normally, we could believe the system runs well.

Specifically, the `run.sh` starts normally if you see "Loading JDK . . .". There would be several exceptions printed out before that, please feel free to ignore them. These exceptions are about logs which will not affect the function of the system. 

Based on our previous conversation, I believe the `propagate.sh` runs normally.



Thank you for all the help!

**Comment by anonymous-002** [comment]
Yes, `propagate.sh` seems to execute normally. Thanks for the PR.

**Comment by blind-reviewer-2** [comment]
Hi Authors,

I was able to get your code running, and it appears functional. However, the data is only available on Github, which is not a "publicly accessible archival repository." Please use a service such as Zenodo, FigShare, or Software Heritage. If this is done within the review period and the link is provided (and later connected to the paper), then I can change my decision regarding the eligibility for the "Available" badge. With this in mind, I cannot recommend the badge of "Available" at this time.

### **Given the current state of the repository, I cannot recommend any badge.**

## Detailed Comments

##### Functional

Installation Comments

- I believe step 3 should be `docker pull xiangzhex/cpc:release`. Currently, it says "push."
- Pulling the docker image took five attempts. Some of the attempts involved network errors and the Docker pull process was not able to recover. For an image the size of yours, this means 2-3 hours of waiting. This is not, at it's core, your problem. However, perhaps you could provide alternatives with more stable ways to get access to that image. 
- I was able to get the code running.

##### Available Badge

Dataset Availability: Only on Github, not a true archival service.
License: Apache

**Comment by XZ-X** [comment]
Thank you for your advice! Now it's on the Zenodo. PR would be made soon.
 [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3660028.svg)](https://doi.org/10.5281/zenodo.3660028)

**Comment by timm** [comment]
@blind-reviewer-2 : given the availability in Zenodo, does that now change your view that 

- _Given the current state of the repository, I cannot recommend any badge._

**Comment by blind-reviewer-2** [comment]
Hi Authors and @timm 

> @blind-reviewer-2 : given the availability in Zenodo, does that now change your view that
> 
> * _Given the current state of the repository, I cannot recommend any badge._

Yes, now that the artefact has been made available in Zenodo I can recommend the badge of **Available**.

**Comment by timm** [comment]
@anonymous-002 : please confirm your current view on the badge "available". I am not 100% clear from the above if your issues were retired by the authors or if you require more changes.

**Comment by anonymous-002** [comment]
Sorry again for the lack of clarity @timm. I agree that the authors apply for both the AVAILABLE badge.

**Comment by timm** [comment]
with no more input the decision here will be "available"

**Comment by blind-reviewer-2** [comment]
Just in case the clarity is lacking from my side: **I recommend the badge of "Available".**
