### ISSUE TITLE
NDStudy

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#97]
https://github.com/researchart/rose6icse/tree/master/submissions/available/NDStudy

# Author Information
The corresponding author for "Near-Duplicate Detection in Web App Model Inference" is:
	```
	RahulKrishna Yandrapally
	GitHub ID: yrahulkr
	Email : rahulyk@ece.ubc.ca
	```

The complete list of Author-University-GitHub ID pairs are as follows:
```
RahulKrishna Yandrapally : University of British Columbia
Andrea Stocco : UniversitÃ  della Svizzera Italiana
Ali Mesbah : University of British Columbia 
```

# applying for Available badge

**Comment by anonreporev** [comment]
I believe we are missing  "A copy of the accepted paper in pdf format."

**Comment by timm** [comment]
@icse-artifact-reviewer @anonreporev and @JonDoe-icse20Artifacts : I look forward to your reviews

**Comment by anonreporev** [comment]
Sorry for the delay.

I've been emailing with the artifact chairs since last week.   I am not able to run the .ova VM on my machine, but this is as I have windows and don't have the necessary permissions to get the VM working.  This is my problem, and not a problem of the repo.

I can at least check some of the artifacts for availability.

I can confirm I can download the ova file in step 1, VirtualBox has a windows-related error when trying to open it.

I have downloaded the datasets and looked at them.
Some more explanation here would help:
What is a state pair and labelled pair?
DS.db, for example, has 1031 rows of name, crawl, numAddedStates, numCrawledStates, crawlTime
where do I find 493K state-pairs and 1000 labelled pairs here?
I don't see the labels as in the ICSE paper.

I have downloaded the crawls and looked at them, one can open and look at the crawled data.
One question:
it's not clear where to find the label in the GroundTruthModels.  Petclinic has an analysis.csv file, but which column in this file is the manual label?
Isn't it misleading to call the file:
GroundTruths for Subjects (GroundTruthModels) - manually labelled
When only the petclinic project in this zip has the ground truth analysis?  How are the other projects used for ground  truth?

Similarly, where is the manual label here?
Crawls used for RQ3 (RQ3Crawls) - manually labelled
Or is it that these crawls were manually labelled in the DS files, but only the crawls are found here.

Because I can't open the .ova file, I can't check the python scripts.  Hopefully someone else with a working virtual machine can try.

I find working Zenodo links for everything.

**Comment by JonDoe-ArtifactsTrack** [comment]
Thank you for your submission. The authors request the Available badge for their work. 
I was able to install the VM that you provide without having to install anything else. However when running it, there are several points that are not clear and that i had to figure out on my own as the details are not provided in your package, plus i get several errors. In particular: 

i. the script to run in the vm is named ‘batchRun_GSComp.sh’ and not ‘runBatch_GSComp.sh’ which is the right name. 

ii. this script it’s not visible using ls command by the cmd, there are some configuration details on the os that have to be fixed. 

iii. it’s not specified where the file ‘htmlCreator.py’ is located, so i had to find it myself.

iv. it’s not clear what you mean by ‘set the location of crawl you want to use as ground truth in (htmlCreator.py)’ 

v. launching htmlCreator.py i got:	
‘’’
ndstudy@ndstudy-VirtualBox:~/NDStudy/comparator/pythonCo	de$ python htmlCreator.py 
Traceback (most recent call last):
  	File "htmlCreator.py", line 2, in <module>
    	from jinja2 import Environment, FileSystemLoader
ImportError: No module named jinja2
‘’’

vi. please specify the line to edit in comparator/pythonCode/runCrawljaxBatch.py

vii. executing runCrawljaxBatch.py i got:
‘’’
ndstudy@ndstudy-VirtualBox:~/NDStudy/comparator/pythonCode$ python runCrawljaxBatch.py 
Traceback (most recent call last):
  	File "runCrawljaxBatch.py", line 3, in <module>
    	import psutil
ImportError: No module named psutil
‘’’

viii. executing python3 comparator/pythonCode/RQ1.py i got:
‘’’
ndstudy@ndstudy-VirtualBox:~/NDStudy/comparator/pythonCo
	e$ python3 RQ1.py
gs_db_data
gt10_db_data
gs_db_data
gt10_db_data
gs_db_data
CONNECTING TO DB 
ERROR CONNECTING TO DB !!!
unable to open database file
ERROR ALL NEARDUPLICATES : where human_classification>=0
'str' object has no attribute 'execute'
NO DB CONNECTION ACTIVE
Traceback (most recent call last):
  	File "RQ1.py", line 257, in <module>
    	getF1_SAF_allrows(allEntries)
 	File "RQ1.py", line 193, in getF1_SAF_allrows
    	print(len(allEntries))
TypeError: object of type 'NoneType' has no len()
‘’’

ix. launching python analyzeCrawl.py i got:
‘’’
ndstudy@ndstudy-VirtualBox:~/NDStudy/comparator$  python analyzeCrawl.py
python: can't open file 'analyzeCrawl.py': [Errno 2] No such file or directory
‘’’

x. the file analyzeCrawl.py is in the folder comparator/pythonCode and trying to launch it i got:
‘’’
python ./analyzeCrawl.py
Traceback (most recent call last):
  	File "./analyzeCrawl.py", line 1, in <module>
    	from runCrawljaxBatch import startProcess, getAllThresholds, getBestThresholds
File "/home/ndstudy/NDStudy/comparator/pythonCode/runCrawljaxBatch.py", line 3, in <module>
    	import psutil
ImportError: No module named psutil
‘’’


So, my conclusion is that the artifact is placed on a publicly accessible archival repository, however as of now, it is not Functional, which is needed for an Available badge.

**Comment by yrahulkr** [comment]
I apologize for the trouble reviewers had to go through running scripts in VM. 

v, vii, x -  the vm has missing python dependencies 
i, ii, iii, iv, v, ix - I will fix the documentation to make things more clear ( all python code is in comparator/PythonCode)
viii - the databases have to be separately downloaded and placed appropriate location (documentation update required) 
 
Can I resubmit after updating the documentation and correcting the dependency issue in vm ?

**Comment by timm** [comment]
@icse-artifact-reviewer  

 @anonreporev 

- authors did an update. can you confirm (or veto) "available"? note that successful execution on YOUR platform is not necessary, as longs you believe there is enough here for successful execution on SOME platform

please advise

**Comment by JonDoe-ArtifactsTrack** [comment]
as i said it is ok for available although not functional on my platform. I assume that it is functional on some platform.

**Comment by anonreporev** [comment]
I did not find it very easy to understand what data is what compared to the paper (see my comments from 3 days ago).  I don't see updates to the readme.    So it's available but not easily understandable.  If this is still available, then the badge applies.

**Comment by yrahulkr** [comment]
Regarding dependencies, I have double checked the problem now. 
You will need to run with "python3" and not "python". Documentation updated accordingly. 

Instructions for other raised issues have also been updated.

**Comment by anonreporev** [comment]
@yrahulkr Also my issues from https://github.com/researchart/rose6icse/issues/97#issuecomment-587483647 ?  If so, where?

**Comment by yrahulkr** [comment]
@anonreporev  sorry, Let me add some more documentation to use the data

**Comment by yrahulkr** [comment]
@anonreporev I have added information regarding using database and ground truth models.

labelling for the other crawls that are used for analysis is found in html_classification after running runAnalysis.py

classification.html shows the data in classification.json

**Comment by timm** [comment]
We are at "available"

but, pending further input, not "reusable"

**Comment by anonreporev** [comment]
Hello,

The new information helps somewhat.  Except the links aren't rendering in md.  Still, it's readable.
"More info on usage [here](https://github.com/NDStudyICSE2019/NDStudy/blob/master/DataSetUsage.md)"

Concerning classification.html, for example
Crawls_complete/RQ3Crawls/allCrawls/petclinic/petclinic_VISUAL_SIFT_83.309_5mins/localhost/crawl0/html_classification/classification.html

Here I see 15Reponses_submitted_out_of_15   and a big green check mark.   It's hard to tell what the results were, 15/15 classified as what?  And as RQ3 was answered automatically, where does 15 come from?

Similarly, the gs.html shows the view where one can choose between clone, near duplicate, and different, but I don't think it shows the (manual) results.   And, of course, it's hard to read the results in the JSON files.  I guess the manual labelling results would be found in DS.db:  "1000 of the rows in nearduplicates have manual labelling (HUMAN_CLASSIFICATION) 0->clone, 1->nearduplicate, 2->different"?

@timm The authors have only asked for available, and yes, it seems everything is there, it's just challenging to parse.

**Comment by yrahulkr** [comment]
@anonreporev 
The html essentially shows all the state-pairs in the crawl. Using the navigation(Load Next, Previous) available on the top of html, you can browse through each state-pair and assign your classification. Instructions link shows the procedure followed in the study to classify a given state-pair.  (Green Mark) shows that all states have been already classified, you can review them by pressing previous. You can also disable "Auto Next" and then it will show all the pairs from the beginning. 

The above instructions are now added to the [documentation](https://github.com/NDStudyICSE2019/NDStudy/blob/master/GoldStandards/readme.md)

**Comment by minkull** [comment]
Converging to available unless @anonreporev and @JonDoe-icse20Artifacts  shout otherwise by 24th Feb AoE.

**Comment by minkull** [comment]
Many thanks everyone for the discussions!

Available awarded.
