### ISSUE TITLE
SolAnalyzer

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#99]
https://github.com/researchart/rose6icse/tree/master/submissions/available/SolAnalyzer
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/SolAnalyzer

- Sungjae Hwang
  - email: sjhwang87@kaist.ac.kr
  - github ids: [sjmini](https://github.com/sjmini)

- Sukyoung Ryu
  - email: sryu.cs@kaist.ac.kr
  - github ids: [sukyoung](https://github.com/sukyoung)

## Note to reviewers: these authors want multiple badges
- reusable
- available

**Comment by sec365** [comment]
The authors apply for the available and reusable badge.

====available====
The tool is open-source at https://github.com/sjmini/icse2020-Solidity/. The authors also released it on Zenodo and provided a DOI.
I have tried to build the tool from source code. The process is clearly documented. I was able to compile and run the tool to analyze the test.sol contract. The result is consistent with what the authors claimed.

**I am happy to recommend the “available” badge.** 

====reusable====
I further tried the tool on smart contracts with known reentrancy vulnerabilities collected from https://github.com/crytic/not-so-smart-contracts. The tool reported some deprecated uses of the throw functions, which seem to be correct. 
The authors also provided guidelines on how to extend the tool. I really appreciate the extensible design and clear documentation.

**A suggestion:** The current analysis result does not contain line numbers. It would be helpful to report the location of the found vulnerabilities.

**I also recommend the “reusable” badge.**

**Comment by timm** [comment]
@andromeda04 : I look forward to your review.

**Comment by andromeda04** [comment]
The authors apply for the "Reusable" and “Available” badges

- **Reusable**: The authors provided two different ways for artifact evaluation: (1) to download VM - all the necessary software is installed in this environment. The tester only needs to run our analyzer in this setup; (2) to clone the repository into the tester's local machine. In this case, sbt, java, and scala must be installed by tester manually.

I have tried both options. The first option worked as expected. I successfully execute the tool located in the repository and applied the test contract. The analyzer detected eight vulnerabilities described in the paper. The result of the analysis was summarized in a file. 
However, I encountered a few problems when cloning the repository into my local machine (option 2). 

1. when running “run tex” in the Build step, I obtained some errors: Expected ‘;’ [Error] bash-3.2$ sbt

2. when running “run test/test.sol” in the Run Test & Result step, I obtained some errors: java.lang.RuntimeException: No main class detected at scala.sys.package$.error(package.scala:30)

stack trace is suppressed; run last compile/ bgRun for the full output 
Compile / bgRun) No main class detected.

- **Available**: The tool is available on Github. It is also available on Zenodo (with a DOI). 

**Recommendation**: As I could successfully use the artifact from the VM, I am happy to recommend both badges for this paper. However, I suggest the authors to solve the executions problems described for the second option (clone the repository).

**Comment by sjmini** [comment]
@sec365 : Thanks for your comment. We will update the tool to print the line numbers.

@andromeda04 : I think you executed the tool with the wrong command.
You should run our tool with "run runTest test/test.sol" not "run test/test.sol".
Moreover, there is no command "run tex". This command is not included in our guidelines.

**Comment by andromeda04** [comment]
**sjmini**: Thanks for pointing out the wrong command. I have tried "run runTest test/test.sol" and it worked as expected. I was able to install and execute the artifact using the two different ways. Therefore, I am happy to recommend the Reusable and Available badges.
